export const MEALS = [
  {
    id: "m1",
    categoryIds: ["c1", "c2"],
    title: "Spaghetti with Tomato Sauce",
    affordability: "affordable",
    complexity: "simple",
    imageUrl:
      "https://www.simplyrecipes.com/thmb/7-Rvs_MNvn7m6MjA-V5exGZgfLI=/2000x1500/filters:no_upscale()/Simply-Recipes-Spaghetti-Tomato-Sauce-Lead-5b8302a0295e4e21a15ef63f257fbc08.jpg",
    duration: 20,
    ingredients: [
      "4 Tomatoes",
      "1 Tablespoon of Olive Oil",
      "1 Onion",
      "250g Spaghetti",
      "Spices",
      "Cheese (optional)",
    ],
    steps: [
      "Cut the tomatoes and the onion into small pieces.",
      "Boil some water - add salt to it once it boils.",
      "Put the spaghetti into the boiling water - they should be done in about 10 to 12 minutes.",
      "In the meantime, heat up some olive oil and add the cut onion.",
      "After 2 minutes, add the tomato pieces, salt, pepper, and your other spices.",
      "The sauce will be done once the spaghetti is finished.",
      "Feel free to add some cheese on top of the finished dish.",
    ],
    isGlutenFree: false,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  },
  {
    id: "m2",
    categoryIds: ["c2"],
    title: "Toast Hawaii",
    affordability: "affordable",
    complexity: "simple",
    imageUrl:
      "https://www.cookingclassy.com/wp-content/uploads/2021/09/french-toast-28.jpg",
    duration: 10,
    ingredients: [
      "1 Slice White Bread",
      "1 Slice Ham",
      "1 Slice Pineapple",
      "1-2 Slices of Cheese",
      "Butter",
    ],
    steps: [
      "Butter one side of the white bread.",
      "Layer ham, pineapple, and cheese on the white bread.",
      "Bake the toast for around 10 minutes in the oven at 200°C.",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  },
  {
    id: "m3",
    categoryIds: ["c3"],
    title: "Classic Hamburger",
    affordability: "pricey",
    complexity: "simple",
    imageUrl:
      "https://www.simplyrecipes.com/thmb/5Z9_7NwxM-wtfszJBrYt7b4Qj9s=/2000x1333/filters:fill(auto,1)/Simply-Recipes-Hamburger-Lead-6-7226896a9f254d9a8e52c8a8e357e700.jpg",
    duration: 45,
    ingredients: [
      "300g Cattle Hack",
      "1 Tomato",
      "1 Cucumber",
      "1 Onion",
      "Ketchup",
      "2 Burger Buns",
    ],
    steps: [
      "Form 2 patties with the cattle hack.",
      "Fry the patties for about 4 minutes on each side.",
      "Quickly fry the buns for about 1 minute on each side.",
      "Brush the buns with ketchup.",
      "Serve the burger with tomato, cucumber, and onion.",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  },
  {
    id: "m4",
    categoryIds: ["c4"],
    title: "Wiener Schnitzel",
    affordability: "luxurious",
    complexity: "challenging",
    imageUrl:
      "https://www.culinaryhill.com/wp-content/uploads/2022/06/Authentic-Wiener-Schnitzel-Culinary-Hill-LR-05.jpg",
    duration: 60,
    ingredients: [
      "8 Veal Cutlets",
      "4 Eggs",
      "200g Bread Crumbs",
      "100g Flour",
      "300ml Butter",
      "100g Vegetable Oil",
      "Salt",
      "Lemon Slices",
    ],
    steps: [
      "Tenderize the veal to about 2–4mm, and season with salt on both sides.",
      "On a flat plate, stir the eggs briefly with a fork.",
      "Lightly coat the cutlets in flour, then dip into the egg, and finally, coat in bread crumbs.",
      "Heat the butter and oil in a large pan (allow the fat to get very hot) and fry the schnitzels until they are golden brown on both sides.",
      "Make sure to toss the pan regularly so that the schnitzels are surrounded by oil and the breading becomes fluffy.",
      "Remove, and drain on kitchen paper. Fry the parsley in the remaining oil and drain.",
      "Place the schnitzels on a plate and serve garnished with parsley and lemon slices.",
    ],
    isGlutenFree: false,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: false,
  },
  {
    id: "m5",
    categoryIds: ["c5"],
    title: "Salad with Smoked Salmon",
    affordability: "luxurious",
    complexity: "simple",
    imageUrl:
      "https://cookieandkate.com/images/2017/07/smoked-salmon-nicoise-salad-recipe-1.jpg",
    duration: 15,
    ingredients: [
      "Arugula",
      "Lamb’s Lettuce",
      "Parsley",
      "Fennel",
      "200g Smoked Salmon",
      "Mustard",
      "Balsamic Vinegar",
      "Olive Oil",
      "Salt and Pepper",
    ],
    steps: [
      "Wash and cut the salad and herbs.",
      "Dice the fennel.",
      "Cut the smoked salmon into cubes.",
      "Process mustard, vinegar, and olive oil into a dressing.",
      "Prepare the salad and put the salmon on top.",
      "Dress with the dressing and serve.",
    ],
    isGlutenFree: true,
    isVegan: false,
    isVegetarian: false,
    isLactoseFree: true,
  },
  {
    id: "m6",
    categoryIds: ["c6", "c10"],
    title: "Exotic Fruit Salad",
    affordability: "affordable",
    complexity: "simple",
    imageUrl:
      "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/exotic-fruit-salad-e2d2e91.jpg",
    duration: 30,
    ingredients: [
      "Mango",
      "Pineapple",
      "Papaya",
      "Kiwi",
      "Passion Fruit",
      "Pomegranate",
      "Mint Leaves",
    ],
    steps: [
      "Peel and dice all the fruits.",
      "Mix them gently in a bowl.",
      "Garnish with mint leaves before serving.",
    ],
    isGlutenFree: true,
    isVegan: true,
    isVegetarian: true,
    isLactoseFree: true,
  },
];
